server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver