drop table if exists Tickets;
drop table if exists Sessions;
drop table if exists Movies;

create table IF NOT EXISTS Movies
(
    id       bigint generated by default as identity primary key,
    name     varchar(50) not null,
    duration int         not null
);

create table IF NOT EXISTS Sessions
(
    id         bigint generated by default as identity primary key,
    movie_id   bigint         not null,
    start_time timestamp      not null,
    price      decimal(10, 2) not null,
    foreign key (movie_id) references Movies (id)
);

create table IF NOT EXISTS Tickets
(
    id         bigint generated by default as identity primary key,
    session_id bigint not null,
    foreign key (session_id) references Sessions (id)
);

insert into Movies (name, duration)
values ('The Shawshank Redemption', 60),
       ('The Godfather', 90),
       ('The Godfather: Part II', 120),
       ('The Dark Knight', 60),
       ('12 Angry Men', 90),
       ('Schindler''s List', 120),
       ('The Lord of the Rings: The Return of the King', 60),
       ('Pulp Fiction', 90),
       ('The Good, the Bad and the Ugly', 120),
       ('The Lord of the Rings: The Fellowship of the Ring', 90);

insert into Sessions (movie_id, start_time, price)
values (1, '2023-04-21 10:00:00', 100),
       (1, '2023-04-21 16:00:00', 300),
       (2, '2023-04-21 10:00:00', 150),
       (3, '2023-04-21 12:00:00', 200),
       (4, '2023-04-21 12:00:00', 100),
       (4, '2023-04-21 19:00:00', 300),
       (5, '2023-04-21 12:00:00', 150),
       (6, '2023-04-21 13:00:00', 200),
       (7, '2023-04-21 14:00:00', 100),
       (8, '2023-04-21 14:00:00', 150),
       (8, '2023-04-21 22:00:00', 400),
       (9, '2023-04-21 17:00:00', 200),
       (10, '2023-04-21 17:00:00', 150);

insert into Tickets (session_id)
values (1),
       (1),
       (1),
       (2),
       (2),
       (3),
       (3),
       (3),
       (3),
       (4),
       (5),
       (6),
       (6),
       (6),
       (7),
       (8),
       (8),
       (8),
       (9),
       (10);
